export * from './Home/Home'
export * from './Settings/Settings'
export * from './Recomended/Recomended'
export * from './Movie/Movie'
export * from './RecommendedList/RecommendedList'
export * from './Login/Login'
export * from './Registration/Registration'
